SELECT
    COUNT(*) AS total_records,
    SUM(CASE WHEN HAZARDTYPE IS NULL THEN 1 ELSE 0 END) AS missing_hazardtype,
    SUM(CASE WHEN STRUCTURECATEGORY IS NULL THEN 1 ELSE 0 END) AS missing_structurecategory,
    SUM(CASE WHEN ROOFCONSTRUCTION IS NULL THEN 1 ELSE 0 END) AS missing_roofmaterial,
    SUM(CASE WHEN EAVES IS NULL THEN 1 ELSE 0 END) AS missing_eaves,
    SUM(CASE WHEN VENTSCREEN IS NULL THEN 1 ELSE 0 END) AS missing_ventscreen,
    SUM(CASE WHEN EXTERIORSIDING IS NULL THEN 1 ELSE 0 END) AS missing_exteriorsiding,
    SUM(CASE WHEN WINDOWPANE IS NULL THEN 1 ELSE 0 END) AS missing_windowpane,
    SUM(CASE WHEN DECKPORCHONGRADE IS NULL THEN 1 ELSE 0 END) AS missing_deckgrade,
    SUM(CASE WHEN DECKPORCHELEVATED IS NULL THEN 1 ELSE 0 END) AS missing_deckelevated,
    SUM(CASE WHEN PATIOCOVERCARPORT IS NULL THEN 1 ELSE 0 END) AS missing_patiocarport,
    SUM(CASE WHEN FENCEATTACHEDTOSTRUCTURE IS NULL THEN 1 ELSE 0 END) AS missing_fenceattached
FROM POSTFIRE;
