SELECT
    INCIDENTNAME,
    INCIDENTSTARTDATE,
    COUNT(*) AS total,
    SUM(CASE WHEN ROOFCONSTRUCTION IS NULL THEN 1 ELSE 0 END) AS missing_roofmaterial
FROM POSTFIRE
GROUP BY INCIDENTNAME
ORDER BY INCIDENTSTARTDATE ASC;