SELECT
    INCIDENTNAME,
    INCIDENTSTARTDATE,
    COUNT(*) AS total,
    SUM(CASE WHEN EAVES IS NULL THEN 1 ELSE 0 END) AS missing_eaves
FROM POSTFIRE
GROUP BY INCIDENTNAME
ORDER BY INCIDENTSTARTDATE ASC;