SELECT
    INCIDENTNAME,
    DAMAGE,
    COUNT(*) AS total,
    SUM(CASE WHEN VENTSCREEN IS NULL THEN 1 ELSE 0 END) AS missing_ventscreen
FROM POSTFIRE
GROUP BY INCIDENTNAME,DAMAGE
ORDER BY INCIDENTSTARTDATE ASC;