SELECT
    INCIDENTNAME,
    INCIDENTSTARTDATE,
    COUNT(*) AS total,
    SUM(CASE WHEN WINDOWPANE IS NULL THEN 1 ELSE 0 END) AS missing_windowpane
FROM POSTFIRE
GROUP BY INCIDENTNAME
ORDER BY INCIDENTSTARTDATE ASC;