SELECT
    INCIDENTNAME,
    COUNT(*) AS total,
    SUM(CASE WHEN DECKPORCHELEVATED IS NULL THEN 1 ELSE 0 END) AS missing_deckelevated
FROM POSTFIRE
GROUP BY INCIDENTNAME
ORDER BY missing_deckelevated DESC;