SELECT
    INCIDENTNAME,
    COUNT(*) AS total,
    SUM(CASE WHEN PATIOCOVERCARPORT IS NULL THEN 1 ELSE 0 END) AS missing_patiocarport
FROM POSTFIRE
GROUP BY INCIDENTNAME
ORDER BY missing_patiocarport DESC;