SELECT
    INCIDENTNAME,
    COUNT(*) AS total,
    SUM(CASE WHEN FENCEATTACHEDTOSTRUCTURE IS NULL THEN 1 ELSE 0 END) AS missing_fenceattached
FROM POSTFIRE
GROUP BY INCIDENTNAME
ORDER BY missing_fenceattached DESC;