SELECT
    ROOFCONSTRUCTION,
    COUNT(*) AS count,
    MIN(INCIDENTNAME) AS example_incident
FROM POSTFIRE
GROUP BY ROOFCONSTRUCTION;


SELECT
    OBJECTID,
    ROOFCONSTRUCTION,
    INCIDENTNAME,
    INCIDENTSTARTDATE,
    DAMAGE,
    APN,
    COUNTY,
    STRUCTURETYPE,
    STRUCTURECATEGORY,
    SITEADDRESS,
    LATITUDE,
    LONGITUDE
FROM POSTFIRE
WHERE ROOFCONSTRUCTION IN (
    'Concrete Slab',
    'No Deck/Porch',
    'Non Combustible'

)
ORDER BY ROOFCONSTRUCTION, COUNTY, INCIDENTNAME;

