SELECT
    VENTSCREEN,
    COUNT(*) AS count,
    MIN(INCIDENTNAME) AS example_incident
FROM POSTFIRE
GROUP BY VENTSCREEN;

SELECT
    OBJECTID,
    VENTSCREEN,
    INCIDENTNAME,
    INCIDENTSTARTDATE,
    DAMAGE,
    APN,
    COUNTY,
    STRUCTURETYPE,
    STRUCTURECATEGORY,
    SITEADDRESS,
    LATITUDE,
    LONGITUDE
FROM POSTFIRE
WHERE VENTSCREEN IN (
    '21-30',
    '>30',
    'Attached Fence',
    'Deck Elevated'

)
ORDER BY VENTSCREEN, COUNTY, INCIDENTNAME;