SELECT
    WINDOWPANE,
    COUNT(*) AS count,
    MIN(INCIDENTNAME) AS example_incident
FROM POSTFIRE
GROUP BY WINDOWPANE;



SELECT
    OBJECTID,
    WINDOWPANE,
    INCIDENTNAME,
    INCIDENTSTARTDATE,
    DAMAGE,
    APN,
    COUNTY,
    STRUCTURETYPE,
    STRUCTURECATEGORY,
    SITEADDRESS,
    LATITUDE,
    LONGITUDE
FROM POSTFIRE
WHERE WINDOWPANE IN (
    'Asphalt',
    'No Deck/Porch',
    'Radiant Heat'

)
ORDER BY WINDOWPANE, COUNTY, INCIDENTNAME;