SELECT
    DECKPORCHONGRADE,
    COUNT(*) AS count,
    MIN(INCIDENTNAME) AS example_incident
FROM POSTFIRE
GROUP BY DECKPORCHONGRADE;


SELECT
    OBJECTID,
    DECKPORCHONGRADE,
    INCIDENTNAME,
    INCIDENTSTARTDATE,
    DAMAGE,
    APN,
    COUNTY,
    STRUCTURETYPE,
    STRUCTURECATEGORY,
    SITEADDRESS,
    LATITUDE,
    LONGITUDE
FROM POSTFIRE
WHERE DECKPORCHONGRADE IN (
    'Metal'

)
ORDER BY DECKPORCHONGRADE, COUNTY, INCIDENTNAME;