SELECT
    DECKPORCHELEVATED,
    COUNT(*) AS count,
    MIN(INCIDENTNAME) AS example_incident
FROM POSTFIRE
GROUP BY DECKPORCHELEVATED;

SELECT
    OBJECTID,
    DECKPORCHELEVATED,
    INCIDENTNAME,
    INCIDENTSTARTDATE,
    DAMAGE,
    APN,
    COUNTY,
    STRUCTURETYPE,
    STRUCTURECATEGORY,
    SITEADDRESS,
    LATITUDE,
    LONGITUDE
FROM POSTFIRE
WHERE DECKPORCHELEVATED IN (
    'Metal'

)
ORDER BY DECKPORCHELEVATED, COUNTY, INCIDENTNAME;
